#!/usr/bin/env python
import os

genivi="git://git.projects.genivi.org/"
github="https://github.com/babynewton/"
giturls = []
giturls.append({"genivi_url":genivi+"smartdevicelink.git",
		"github_url":github+"smartdevicelink", 
		"branch":"master",
		"path":"../core"})
giturls.append({"genivi_url":genivi+"smartdevicelink.git",
		"github_url":github+"smartdevicelink",
		"branch":"release_1.0",
		"path":"../core_r1"})
giturls.append({"genivi_url":genivi+"smartdevicelink_android.git",
		"github_url":github+"smartdevicelink_android",
		"branch":"master",
		"path":"../android"})
giturls.append({"genivi_url":genivi+"smartdevicelink_tester_android.git",
		"github_url":github+"smartdevicelink_test_android",
		"branch":"master",
		"path":"../tester_android"})

for x in giturls:
	if os.path.exists(x["path"]):
		owd=os.getcwd()
		os.chdir(x["path"])
		cmd='git pull origin ' + x["branch"]
		cmd='git pull genivi ' + x["branch"]
		os.system(cmd)
		os.chdir(owd)
	else:
		cmd='git clone ' + x["github_url"] + ' -b ' + x["branch"] + ' ' + x["path"]
		os.system(cmd)
		owd=os.getcwd()
		os.chdir(x["path"])
		cmd='git remote add genivi ' + x["genivi_url"]
		os.system(cmd)
		os.chdir(owd)
